In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
myData = pd.read_csv('mycar.xls')

In [4]:
X = myData.iloc[:,:-1].values
Y = myData.iloc[:,1].values

In [5]:
from sklearn.model_selection import train_test_split

In [6]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size= 0.3)

In [7]:
from sklearn.linear_model import LinearRegression
myModel = LinearRegression() #Обозначаем, что наша модель - линейная регрессия
myModel.fit(X_train,Y_train) #обучаем модель на обучающих данных

LinearRegression()

In [8]:
y_pred = myModel.predict(X_test)
y_pred

array([-1.62642786, 42.26614211, 62.21731028, 34.28567485, 42.26614211,
       10.34427304, 38.27590848, 70.19777755, 62.21731028, 18.32474031,
       62.21731028, 62.21731028, 46.25637575, 74.18801118, 34.28567485])

In [11]:
myData

Speed  Stopping_dist
0       4              2
1       4             10
2       7              4
3       7             22
4       8             16
5       9             10
6      10             18
7      10             26
8      10             34
9      11             17
10     11             28
11     12             14
12     12             20
13     12             24
14     12             28
15     13             26
16     13             34
17     13             34
18     13             46
19     14             26
20     14             36
21     14             60
22     14             80
23     15             20
24     15             26
25     15             54
26     16             32
27     16             40
28     17             32
29     17             40
30     17             50
31     18             42
32     18             56
33     18             76
34     18             84
35     19             36
36     19             46
37     19             68
38     20             32
39     20             48
40     20             52
41     20             56
42     20             64
43     22             66
44     23             54
45     24             70
46     24             92
47     24             93
48     25             85

In [12]:
X

array([[ 4],
       [ 4],
       [ 7],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [10],
       [10],
       [11],
       [11],
       [12],
       [12],
       [12],
       [12],
       [13],
       [13],
       [13],
       [13],
       [14],
       [14],
       [14],
       [14],
       [15],
       [15],
       [15],
       [16],
       [16],
       [17],
       [17],
       [17],
       [18],
       [18],
       [18],
       [18],
       [19],
       [19],
       [19],
       [20],
       [20],
       [20],
       [20],
       [20],
       [22],
       [23],
       [24],
       [24],
       [24],
       [25]])

In [13]:
Y

array([ 2, 10,  4, 22, 16, 10, 18, 26, 34, 17, 28, 14, 20, 24, 28, 26, 34,
       34, 46, 26, 36, 60, 80, 20, 26, 54, 32, 40, 32, 40, 50, 42, 56, 76,
       84, 36, 46, 68, 32, 48, 52, 56, 64, 66, 54, 70, 92, 93, 85])

In [14]:
import pandas as pd               # библиотека для работы с таблицами
import numpy as np                # библиотека для работы с матрицами

In [15]:
y_happy = [4,20,110,15,23]

In [16]:
y_happy_pred = [5,15,100,9,21]

In [17]:
from sklearn import metrics  # подгружаем метрики

In [18]:
#Вычисляем MAE:

MAE = metrics.mean_absolute_error(y_happy, y_happy_pred)

print(MAE)

4.8


In [19]:
#Вычисляем MSE:

MSE = metrics.mean_squared_error(y_happy, y_happy_pred)
print(MSE)

33.2


In [20]:
#Вычисляем коэффициент детерминации:

R_2 = metrics.r2_score(y_happy, y_happy_pred)
print(R_2)

0.9774247946472284


In [22]:
y_true = [2, 3, -1, 4]
y_pred = [1, 3, 2, 5]
#Вычисляем MSE:

MSE = metrics.mean_squared_error(y_true, y_pred)
print(MSE)

2.75
