In [1]:
import numpy as np
import pandas as pd

In [2]:
np.empty(5)

array([ 3.10503618e+231, -1.29074495e-231,  1.48219694e-323,
        0.00000000e+000,  0.00000000e+000])

In [3]:
np.zeros((10, 7)) 

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [4]:
np.ones((3,3,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [5]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [6]:
np.full((3, 5), 3.14) 

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [7]:
np.arange(0, 21, 7)

array([ 0,  7, 14])

In [8]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [9]:
np.random.randint(0, 10, (3, 3))

array([[1, 3, 4],
       [1, 8, 3],
       [7, 1, 2]])

In [10]:
my_secret = [x for x in range(1, 301, 7) if x%10 == 7 or x%10 == 1]
np.array([my_secret, [x/2 for x in my_secret], [x-100 for x in my_secret]])

array([[  1. ,  57. ,  71. , 127. , 141. , 197. , 211. , 267. , 281. ],
       [  0.5,  28.5,  35.5,  63.5,  70.5,  98.5, 105.5, 133.5, 140.5],
       [-99. , -43. , -29. ,  27. ,  41. ,  97. , 111. , 167. , 181. ]])

In [11]:
my_secret

[1, 57, 71, 127, 141, 197, 211, 267, 281]

In [12]:
np.array([i for i in range(11) if i%2])

array([1, 3, 5, 7, 9])

In [13]:
[x for x in range(1, 301, 7)] 

[1,
 8,
 15,
 22,
 29,
 36,
 43,
 50,
 57,
 64,
 71,
 78,
 85,
 92,
 99,
 106,
 113,
 120,
 127,
 134,
 141,
 148,
 155,
 162,
 169,
 176,
 183,
 190,
 197,
 204,
 211,
 218,
 225,
 232,
 239,
 246,
 253,
 260,
 267,
 274,
 281,
 288,
 295]

In [53]:
first_line = [x*y for x in range(2, 100, 6) for y in range (7, 1, -2)]
second_line = [x ** 0.5 for x in range(1000, 1101, 2)]
third_line = [x**2 for x in range(51)]

big_secret = np.array([first_line, second_line, third_line, second_line, first_line])

In [15]:
big_secret

array([[1.40000000e+01, 1.00000000e+01, 6.00000000e+00, 5.60000000e+01,
        4.00000000e+01, 2.40000000e+01, 9.80000000e+01, 7.00000000e+01,
        4.20000000e+01, 1.40000000e+02, 1.00000000e+02, 6.00000000e+01,
        1.82000000e+02, 1.30000000e+02, 7.80000000e+01, 2.24000000e+02,
        1.60000000e+02, 9.60000000e+01, 2.66000000e+02, 1.90000000e+02,
        1.14000000e+02, 3.08000000e+02, 2.20000000e+02, 1.32000000e+02,
        3.50000000e+02, 2.50000000e+02, 1.50000000e+02, 3.92000000e+02,
        2.80000000e+02, 1.68000000e+02, 4.34000000e+02, 3.10000000e+02,
        1.86000000e+02, 4.76000000e+02, 3.40000000e+02, 2.04000000e+02,
        5.18000000e+02, 3.70000000e+02, 2.22000000e+02, 5.60000000e+02,
        4.00000000e+02, 2.40000000e+02, 6.02000000e+02, 4.30000000e+02,
        2.58000000e+02, 6.44000000e+02, 4.60000000e+02, 2.76000000e+02,
        6.86000000e+02, 4.90000000e+02, 2.94000000e+02],
       [3.16227766e+01, 3.16543836e+01, 3.16859590e+01, 3.17175031e+01,
       

In [16]:
np.shape(big_secret)

(5, 51)

In [20]:
element_sum = 0
for x in range(0, 5):
    element_sum += big_secret[x][50]
print(round(element_sum, 2))

3154.33


In [22]:
new_secret = np.array([big_secret[0][:5], big_secret[1][:5],  big_secret[2][:5], big_secret[3][:5],  big_secret[4][:5]])
new_secret

array([[14.        , 10.        ,  6.        , 56.        , 40.        ],
       [31.6227766 , 31.65438358, 31.68595904, 31.71750305, 31.74901573],
       [ 0.        ,  1.        ,  4.        ,  9.        , 16.        ],
       [31.6227766 , 31.65438358, 31.68595904, 31.71750305, 31.74901573],
       [14.        , 10.        ,  6.        , 56.        , 40.        ]])

In [23]:
new_secret1 = big_secret[:, :5]
new_secret1

array([[14.        , 10.        ,  6.        , 56.        , 40.        ],
       [31.6227766 , 31.65438358, 31.68595904, 31.71750305, 31.74901573],
       [ 0.        ,  1.        ,  4.        ,  9.        , 16.        ],
       [31.6227766 , 31.65438358, 31.68595904, 31.71750305, 31.74901573],
       [14.        , 10.        ,  6.        , 56.        , 40.        ]])

In [38]:
diag_sum = 0
y = 0
for x in range(0, 5):
    diag_sum += new_secret1[x][y]
    y += 1
print(round(diag_sum, 2))

121.37


In [40]:
new_secret2 = big_secret[:, -5:]
new_secret2

array([[ 460.        ,  276.        ,  686.        ,  490.        ,
         294.        ],
       [  33.04542328,   33.07567082,   33.10589071,   33.13608305,
          33.1662479 ],
       [2116.        , 2209.        , 2304.        , 2401.        ,
        2500.        ],
       [  33.04542328,   33.07567082,   33.10589071,   33.13608305,
          33.1662479 ],
       [ 460.        ,  276.        ,  686.        ,  490.        ,
         294.        ]])

In [43]:
diag_mult = 1
y = 0
for x in range(0, 5):
    diag_mult *= new_secret2[x][y]
    y += 1
print(diag_mult)

341505315559.2347


In [44]:
my_array = np.random.randint(1, 100, (4, 6)) 

In [45]:
my_array

array([[27, 87, 30, 24, 11, 73],
       [45, 25, 84, 36, 25, 83],
       [25, 46, 34, 43, 19, 78],
       [62, 10, 51, 97, 25, 77]])

In [46]:
my_slice = my_array[1:3, 2:4]

In [47]:
my_slice

array([[84, 36],
       [34, 43]])

In [48]:
my_slice[:] = 0

In [49]:
my_array

array([[27, 87, 30, 24, 11, 73],
       [45, 25,  0,  0, 25, 83],
       [25, 46,  0,  0, 19, 78],
       [62, 10, 51, 97, 25, 77]])

In [54]:
for x in range(0, 5):
    for y in range(0, 51):
        if x%2 == 0 and y%2 == 0:
            big_secret[x][y] = -1
        elif x%2 != 0 and y%2 != 0:
            big_secret[x][y] = 1
            
big_secret

array([[-1.00000000e+00,  1.00000000e+01, -1.00000000e+00,
         5.60000000e+01, -1.00000000e+00,  2.40000000e+01,
        -1.00000000e+00,  7.00000000e+01, -1.00000000e+00,
         1.40000000e+02, -1.00000000e+00,  6.00000000e+01,
        -1.00000000e+00,  1.30000000e+02, -1.00000000e+00,
         2.24000000e+02, -1.00000000e+00,  9.60000000e+01,
        -1.00000000e+00,  1.90000000e+02, -1.00000000e+00,
         3.08000000e+02, -1.00000000e+00,  1.32000000e+02,
        -1.00000000e+00,  2.50000000e+02, -1.00000000e+00,
         3.92000000e+02, -1.00000000e+00,  1.68000000e+02,
        -1.00000000e+00,  3.10000000e+02, -1.00000000e+00,
         4.76000000e+02, -1.00000000e+00,  2.04000000e+02,
        -1.00000000e+00,  3.70000000e+02, -1.00000000e+00,
         5.60000000e+02, -1.00000000e+00,  2.40000000e+02,
        -1.00000000e+00,  4.30000000e+02, -1.00000000e+00,
         6.44000000e+02, -1.00000000e+00,  2.76000000e+02,
        -1.00000000e+00,  4.90000000e+02, -1.00000000e+0

In [55]:
new_secret3 = big_secret[:, :5]
new_secret3

array([[-1.        , 10.        , -1.        , 56.        , -1.        ],
       [31.6227766 ,  1.        , 31.68595904,  1.        , 31.74901573],
       [-1.        ,  1.        , -1.        ,  9.        , -1.        ],
       [31.6227766 ,  1.        , 31.68595904,  1.        , 31.74901573],
       [-1.        , 10.        , -1.        , 56.        , -1.        ]])

In [56]:
diag_sum = 0
y = 0
for x in range(0, 5):
    diag_sum += new_secret1[x][y]
    y += 1
print(diag_sum)

-1.0


In [57]:
new_secret4 = big_secret[:, -5:]
new_secret4

array([[-1.00000000e+00,  2.76000000e+02, -1.00000000e+00,
         4.90000000e+02, -1.00000000e+00],
       [ 3.30454233e+01,  1.00000000e+00,  3.31058907e+01,
         1.00000000e+00,  3.31662479e+01],
       [-1.00000000e+00,  2.20900000e+03, -1.00000000e+00,
         2.40100000e+03, -1.00000000e+00],
       [ 3.30454233e+01,  1.00000000e+00,  3.31058907e+01,
         1.00000000e+00,  3.31662479e+01],
       [-1.00000000e+00,  2.76000000e+02, -1.00000000e+00,
         4.90000000e+02, -1.00000000e+00]])

In [58]:
diag_mult = 1
y = 0
for x in range(0, 5):
    diag_mult *= new_secret4[x][y]
    y += 1
print(diag_mult)

-1.0


In [59]:
a = np.array([3,6,9])
b = np.array([12,15,18])

result1 = a+b
result2 = b-a
result3 = a*b
result4 = a/b
result5 = a*2
print('Сумма: {}\nРазность: {}\nПроизведение: {}\nЧастное: {}\nУмножение на число: {}'.format(result1, result2, result3, result4, result5))

Сумма: [15 21 27]
Разность: [9 9 9]
Произведение: [ 36  90 162]
Частное: [0.25 0.4  0.5 ]
Умножение на число: [ 6 12 18]


In [60]:
my_array = np.array([[1,2,3,4,5], [6,7,8,9,10]])
my_array.T

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

In [61]:
my_array = np.random.randint(0, 10, 20)
my_array.reshape((4,5))

array([[2, 1, 3, 2, 8],
       [4, 7, 9, 7, 5],
       [3, 1, 0, 9, 8],
       [3, 9, 0, 7, 6]])

In [62]:
my_array = np.array([[1,2,3], [11,22,33], [111,222,333]])

In [63]:
my_array

array([[  1,   2,   3],
       [ 11,  22,  33],
       [111, 222, 333]])

In [64]:
my_array.flatten()

array([  1,   2,   3,  11,  22,  33, 111, 222, 333])

In [65]:
my_array = np.random.randint(0, 10, (3,4))

In [66]:
my_array

array([[1, 4, 8, 2],
       [7, 7, 7, 6],
       [9, 4, 9, 9]])

In [67]:
my_array<5

array([[ True,  True, False,  True],
       [False, False, False, False],
       [False,  True, False, False]])

In [68]:
my_array[my_array<5]

array([1, 4, 2, 4])

In [69]:
mask = np.array([1, 0, 1, 0], dtype=bool)
my_array[:, mask]

array([[1, 8],
       [7, 7],
       [9, 9]])

In [70]:
my_array = np.random.randint(0, 10, (4, 6))

In [71]:
my_array

array([[8, 8, 5, 3, 1, 8],
       [6, 6, 9, 3, 3, 2],
       [6, 6, 4, 7, 6, 6],
       [2, 3, 9, 0, 2, 8]])

In [72]:
np.sort(my_array, axis=1)

array([[1, 3, 5, 8, 8, 8],
       [2, 3, 3, 6, 6, 9],
       [4, 6, 6, 6, 6, 7],
       [0, 2, 2, 3, 8, 9]])

In [73]:
np.sort(my_array, axis=0)

array([[2, 3, 4, 0, 1, 2],
       [6, 6, 5, 3, 2, 6],
       [6, 6, 9, 3, 3, 8],
       [8, 8, 9, 7, 6, 8]])

In [95]:
first = [x**(1/2) for x in range(100)]
second = [x**(1/3) for x in range(100, 200)]
third = [x/y for x in range(200,300,2) for y in [3,5]]

great_secret = np.array([first, second, third]).T

In [75]:
np.shape(great_secret)

(100, 3)

In [77]:
row = great_secret[0, :]

In [78]:
row

array([ 0.        ,  4.64158883, 66.66666667])

In [79]:
cos_row = np.cos(row)
cos_row

array([ 1.        , -0.07074101, -0.76919177])

In [82]:
sum = 0
for x in range(0, 3):
    sum += cos_row[x]
print(round(sum, 2))

0.16


In [84]:
great_secret1 = great_secret[great_secret > 50]

In [85]:
great_secret1

array([66.66666667, 67.33333333, 68.        , 68.66666667, 69.33333333,
       70.        , 70.66666667, 71.33333333, 72.        , 72.66666667,
       73.33333333, 74.        , 74.66666667, 75.33333333, 76.        ,
       76.66666667, 77.33333333, 78.        , 78.66666667, 79.33333333,
       80.        , 80.66666667, 81.33333333, 82.        , 82.66666667,
       83.33333333, 84.        , 50.4       , 84.66666667, 50.8       ,
       85.33333333, 51.2       , 86.        , 51.6       , 86.66666667,
       52.        , 87.33333333, 52.4       , 88.        , 52.8       ,
       88.66666667, 53.2       , 89.33333333, 53.6       , 90.        ,
       54.        , 90.66666667, 54.4       , 91.33333333, 54.8       ,
       92.        , 55.2       , 92.66666667, 55.6       , 93.33333333,
       56.        , 94.        , 56.4       , 94.66666667, 56.8       ,
       95.33333333, 57.2       , 96.        , 57.6       , 96.66666667,
       58.        , 97.33333333, 58.4       , 98.        , 58.8 

In [86]:
np.shape(great_secret1)

(74,)

In [87]:
sum1 = 0
for x in range(0, len(great_secret1)):
    sum1 += great_secret1[x]
print(sum1)

5470.0


In [93]:
great_secret = great_secret.flatten()

In [94]:
great_secret[150]

7.0710678118654755

In [99]:
great_secret = np.sort(great_secret, axis = 0)

In [100]:
np.shape(great_secret)

(100, 3)

In [101]:
last_row = great_secret[99, :]
sum_last = 0
for x in range(0, 3):
    sum_last += last_row[x]
print(round(sum_last, 2))

115.12


In [102]:
my_array = np.array([[1,2,3,4,5],
                     [6,7,8,9,10],
                     [11,12,13,14,15],
                     [16,17,18,19,20],
                     [21,22,23,24,25]])

In [103]:
my_array

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [105]:
my_array[1:4, 1:4]

array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])

In [112]:
students = np.array([[1, 135, 34, 4],
                    [2, 160, 43, 5],
                    [3, 163, 40, 4.3],
                    [4, 147, 44, 5],
                    [5, 138, 41, 4.7],
                    [6, 149, 54, 3.9],
                    [7, 136, 39, 4.2],
                    [8, 154, 48, 4.9],
                    [9, 137, 35, 3.7],
                    [10, 164, 60, 4.6]])

In [113]:
students

array([[  1. , 135. ,  34. ,   4. ],
       [  2. , 160. ,  43. ,   5. ],
       [  3. , 163. ,  40. ,   4.3],
       [  4. , 147. ,  44. ,   5. ],
       [  5. , 138. ,  41. ,   4.7],
       [  6. , 149. ,  54. ,   3.9],
       [  7. , 136. ,  39. ,   4.2],
       [  8. , 154. ,  48. ,   4.9],
       [  9. , 137. ,  35. ,   3.7],
       [ 10. , 164. ,  60. ,   4.6]])

In [114]:
mean = np.mean(students[:,-1])
mean

4.430000000000001

In [115]:
median = np.median(students[:,-1])
median

4.449999999999999

In [116]:
sort = np.sort(students[:,-1])
(sort[4]+sort[5])/2

4.449999999999999

In [117]:
median_mass = np.median(students[:, 2])
median_mass

42.0

In [118]:
mean_mass = np.mean(students[:, 2])
mean_mass
print(mean_mass - median_mass)

1.7999999999999972


In [119]:
mean_mass

43.8

In [120]:
corr = np.corrcoef(students[:,1], students[:,2])
corr

array([[1.        , 0.63270447],
       [0.63270447, 1.        ]])

In [121]:
corr1 = np.corrcoef(students[:, 1], students[:, 3])
corr1

array([[1.       , 0.4657055],
       [0.4657055, 1.       ]])

In [122]:
corr2 = np.corrcoef(students[:, 2], students[:, 3])
corr2

array([[1.        , 0.29801325],
       [0.29801325, 1.        ]])

In [123]:
std = np.std(students[:,1])
std

10.93663568013491

In [124]:
std_score = np.std(students[:,3])
std_score

0.4517742799230607

In [125]:
std_weight = np.std(students[:,2])
std_weight**2

60.36

In [126]:
my_array = np.array([[1,2,3,4,5],
                     [6,7,8,9,10],
                     [11,12,13,14,15],
                     [16,17,18,19,20],
                     [21,22,23,24,25]])
my_sin = np.sin(my_array)
my_sin

array([[ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427],
       [-0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111],
       [-0.99999021, -0.53657292,  0.42016704,  0.99060736,  0.65028784],
       [-0.28790332, -0.96139749, -0.75098725,  0.14987721,  0.91294525],
       [ 0.83665564, -0.00885131, -0.8462204 , -0.90557836, -0.13235175]])

In [133]:
sum_sin = 0
for x in range(0, 5):
    for y in range(0, 5):
        sum_sin += my_sin[x, y]
print(round(sum_sin, 3))

7.572


In [128]:
np.shape(my_sin)

(5, 5)

In [130]:
my_sin[1:4, 1:4] = 1

In [132]:
my_sin

array([[ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427],
       [-0.2794155 ,  1.        ,  1.        ,  1.        , -0.54402111],
       [-0.99999021,  1.        ,  1.        ,  1.        ,  0.65028784],
       [-0.28790332,  1.        ,  1.        ,  1.        ,  0.91294525],
       [ 0.83665564, -0.00885131, -0.8462204 , -0.90557836, -0.13235175]])

In [134]:
my_sin_new = my_sin[:, :4]
my_sin_new

array([[ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ],
       [-0.2794155 ,  1.        ,  1.        ,  1.        ],
       [-0.99999021,  1.        ,  1.        ,  1.        ],
       [-0.28790332,  1.        ,  1.        ,  1.        ],
       [ 0.83665564, -0.00885131, -0.8462204 , -0.90557836]])

In [135]:
my_sin

array([[ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427],
       [-0.2794155 ,  1.        ,  1.        ,  1.        , -0.54402111],
       [-0.99999021,  1.        ,  1.        ,  1.        ,  0.65028784],
       [-0.28790332,  1.        ,  1.        ,  1.        ,  0.91294525],
       [ 0.83665564, -0.00885131, -0.8462204 , -0.90557836, -0.13235175]])

In [138]:
my_sin_new = my_sin_new.reshape((10, 2))

In [139]:
my_sin_new

array([[ 0.84147098,  0.90929743],
       [ 0.14112001, -0.7568025 ],
       [-0.2794155 ,  1.        ],
       [ 1.        ,  1.        ],
       [-0.99999021,  1.        ],
       [ 1.        ,  1.        ],
       [-0.28790332,  1.        ],
       [ 1.        ,  1.        ],
       [ 0.83665564, -0.00885131],
       [-0.8462204 , -0.90557836]])

In [145]:
sum_row = 0
for x in range(0, 10):
    sum_row += my_sin_new[x, 0]
print(round(sum_row, 3))

2.406


In [147]:
bigdata = np.array([x**2 for x in range(100, 1001) if x%2 != 0])
bigdata

array([ 10201,  10609,  11025,  11449,  11881,  12321,  12769,  13225,
        13689,  14161,  14641,  15129,  15625,  16129,  16641,  17161,
        17689,  18225,  18769,  19321,  19881,  20449,  21025,  21609,
        22201,  22801,  23409,  24025,  24649,  25281,  25921,  26569,
        27225,  27889,  28561,  29241,  29929,  30625,  31329,  32041,
        32761,  33489,  34225,  34969,  35721,  36481,  37249,  38025,
        38809,  39601,  40401,  41209,  42025,  42849,  43681,  44521,
        45369,  46225,  47089,  47961,  48841,  49729,  50625,  51529,
        52441,  53361,  54289,  55225,  56169,  57121,  58081,  59049,
        60025,  61009,  62001,  63001,  64009,  65025,  66049,  67081,
        68121,  69169,  70225,  71289,  72361,  73441,  74529,  75625,
        76729,  77841,  78961,  80089,  81225,  82369,  83521,  84681,
        85849,  87025,  88209,  89401,  90601,  91809,  93025,  94249,
        95481,  96721,  97969,  99225, 100489, 101761, 103041, 104329,
      

In [148]:
bigdata_med = np.median(bigdata)

In [149]:
bigdata_med

302501.0

In [150]:
bigdata_std = np.std(bigdata)
print(round(bigdata_std))

292095.0


In [154]:
bigdata_corr = np.corrcoef(bigdata[0:450:2], bigdata[1:451:2])
bigdata_corr

array([[1.        , 0.99999973],
       [0.99999973, 1.        ]])